apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world-helm-chart.fullname" . }}
  labels:
    {{- include "hello-world-helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app.kubernetes.io/name: {{ include "hello-world-helm-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

